### ISSUE TITLE
Additional Environment Variables

### ISSUE THREAD

**Issue by RumBugen** [1995parham/kener-chart#6]
You currently have a set of four environment variables that can be set. 
It would be nice to have an option in the values like "extraEnvVars" and/or "envFrom" to set [additional environment variables](https://kener.ing/docs/environment-vars).

For example:
```yaml
extraEnvVars:
      - name: TZ # Timezone
        value: "Europe/Berlin"
      - name: SMTP_HOST # SMTP
        value: "smtp.example.com"
      - name: SMTP_PORT
        value: 587
      - name: SMTP_USER
        value: "test@example.com"
      # and so on

envFrom:
    - secretRef:
        name: env-secret
```
